(part "TPS51206DSQR"
    (packageRef "SON40P200X200X80-11N")
    (interface
        (port "1" (symbPinId 1) (portName "VDDQSNS") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VLDOIN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VTT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PGND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VTTSNS") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VTTREF") (portType INOUT))
        (port "7" (symbPinId 7) (portName "S3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND") (portType INOUT))
        (port "9" (symbPinId 9) (portName "S5") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VDD") (portType INOUT))
        (port "11" (symbPinId 11) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS51206DSQR")
    (property "Mouser_Part_Number" "595-TPS51206DSQR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS51206DSQR?qs=%252BG2H6gVb6ixLbD%2FQxTGyiQ%3D%3D")
    (property "Arrow_Part_Number" "TPS51206DSQR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tps51206dsqr/texas-instruments?region=nac")
    (property "Description" "2A Peak Sink/Source DDR Termination Regulator with VTTREF Buffered Reference for DDR2/3/3L/4")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/tps51206.pdf")
    (property "symbolName1" "TPS51206DSQR")
)
