SamacSys ECAD Model
228846/1018887/2.50/11/3/Integrated Circuit

DESIGNSPARK_INTERMEDIATE_ASCII

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "r70_20"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 0.2) (shapeHeight 0.7))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(padStyleDef "r160_100"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 1) (shapeHeight 1.6))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(textStyleDef "Default"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 50 mils)
			(strokeWidth 5 mils)
		)
	)
	(patternDef "SON40P200X200X80-11N" (originalName "SON40P200X200X80-11N")
		(multiLayer
			(pad (padNum 1) (padStyleRef r70_20) (pt -1.05, 0.8) (rotation 90))
			(pad (padNum 2) (padStyleRef r70_20) (pt -1.05, 0.4) (rotation 90))
			(pad (padNum 3) (padStyleRef r70_20) (pt -1.05, 0) (rotation 90))
			(pad (padNum 4) (padStyleRef r70_20) (pt -1.05, -0.4) (rotation 90))
			(pad (padNum 5) (padStyleRef r70_20) (pt -1.05, -0.8) (rotation 90))
			(pad (padNum 6) (padStyleRef r70_20) (pt 1.05, -0.8) (rotation 90))
			(pad (padNum 7) (padStyleRef r70_20) (pt 1.05, -0.4) (rotation 90))
			(pad (padNum 8) (padStyleRef r70_20) (pt 1.05, 0) (rotation 90))
			(pad (padNum 9) (padStyleRef r70_20) (pt 1.05, 0.4) (rotation 90))
			(pad (padNum 10) (padStyleRef r70_20) (pt 1.05, 0.8) (rotation 90))
			(pad (padNum 11) (padStyleRef r160_100) (pt 0, 0) (rotation 0))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt 0, 0) (textStyleRef "Default") (isVisible True))
		)
		(layerContents (layerNumRef 30)
			(line (pt -1.625 1.3) (pt 1.625 1.3) (width 0.05))
		)
		(layerContents (layerNumRef 30)
			(line (pt 1.625 1.3) (pt 1.625 -1.3) (width 0.05))
		)
		(layerContents (layerNumRef 30)
			(line (pt 1.625 -1.3) (pt -1.625 -1.3) (width 0.05))
		)
		(layerContents (layerNumRef 30)
			(line (pt -1.625 -1.3) (pt -1.625 1.3) (width 0.05))
		)
		(layerContents (layerNumRef 28)
			(line (pt -1 1) (pt 1 1) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt 1 1) (pt 1 -1) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt 1 -1) (pt -1 -1) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt -1 -1) (pt -1 1) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt -1 0.5) (pt -0.5 1) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(arc (pt -1.4, 1.4) (radius 0.125) (startAngle 0.0) (sweepAngle 0.0) (width 0.25))
		)
		(layerContents (layerNumRef 18)
			(arc (pt -1.4, 1.4) (radius 0.125) (startAngle 180.0) (sweepAngle 180.0) (width 0.25))
		)
	)
	(symbolDef "TPS51206DSQR" (originalName "TPS51206DSQR")

		(pin (pinNum 1) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -25 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 2) (pt 0 mils -100 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -125 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 3) (pt 0 mils -200 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -225 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 4) (pt 0 mils -300 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -325 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 5) (pt 0 mils -400 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -425 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 6) (pt 700 mils -900 mils) (rotation 90) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 725 mils -670 mils) (rotation 90]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 7) (pt 1400 mils 0 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 1170 mils -25 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 8) (pt 1400 mils -100 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 1170 mils -125 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 9) (pt 1400 mils -200 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 1170 mils -225 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 10) (pt 1400 mils -300 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 1170 mils -325 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 11) (pt 1400 mils -400 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 1170 mils -425 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(line (pt 200 mils 100 mils) (pt 1200 mils 100 mils) (width 6 mils))
		(line (pt 1200 mils 100 mils) (pt 1200 mils -700 mils) (width 6 mils))
		(line (pt 1200 mils -700 mils) (pt 200 mils -700 mils) (width 6 mils))
		(line (pt 200 mils -700 mils) (pt 200 mils 100 mils) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 1250 mils 300 mils) (justify Left) (isVisible True) (textStyleRef "Default"))

	)
	(compDef "TPS51206DSQR" (originalName "TPS51206DSQR") (compHeader (numPins 11) (numParts 1) (refDesPrefix IC)
		)
		(compPin "1" (pinName "VDDQSNS") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "2" (pinName "VLDOIN") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "3" (pinName "VTT") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "4" (pinName "PGND") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "5" (pinName "VTTSNS") (partNum 1) (symPinNum 5) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "11" (pinName "EP") (partNum 1) (symPinNum 6) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "10" (pinName "VDD") (partNum 1) (symPinNum 7) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "9" (pinName "S5") (partNum 1) (symPinNum 8) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "8" (pinName "GND") (partNum 1) (symPinNum 9) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "7" (pinName "S3") (partNum 1) (symPinNum 10) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "6" (pinName "VTTREF") (partNum 1) (symPinNum 11) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "TPS51206DSQR"))
		(attachedPattern (patternNum 1) (patternName "SON40P200X200X80-11N")
			(numPads 11)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
				(padNum 3) (compPinRef "3")
				(padNum 4) (compPinRef "4")
				(padNum 5) (compPinRef "5")
				(padNum 6) (compPinRef "6")
				(padNum 7) (compPinRef "7")
				(padNum 8) (compPinRef "8")
				(padNum 9) (compPinRef "9")
				(padNum 10) (compPinRef "10")
				(padNum 11) (compPinRef "11")
			)
		)
		(attr "Manufacturer_Name" "Texas Instruments")
		(attr "Manufacturer_Part_Number" "TPS51206DSQR")
		(attr "Mouser Part Number" "595-TPS51206DSQR")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS51206DSQR?qs=%252BG2H6gVb6ixLbD%2FQxTGyiQ%3D%3D")
		(attr "Arrow Part Number" "TPS51206DSQR")
		(attr "Arrow Price/Stock" "https://www.arrow.com/en/products/tps51206dsqr/texas-instruments?region=nac")
		(attr "Description" "2A Peak Sink/Source DDR Termination Regulator with VTTREF Buffered Reference for DDR2/3/3L/4")
		(attr "Datasheet Link" "http://www.ti.com/lit/ds/symlink/tps51206.pdf")
		(attr "Height" "0.8 mm")
	)

)
